version: '3.4'


services:
  presentation:
    image: recipeapp.presentation
    container_name: recipeapp.presentation
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080 
    ports:
        - 8080:80
    depends_on:
        - service
    
  


  service:
    image: recipeapp.service
    container_name: recipeapp.service
    build:
      context: .
      dockerfile: Service/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
    ports:
        - 8081:80





  database:
    build: ./mssql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sqlserver!Password"
    ports:
      - 1450:1433   # exposed so we can connect via ssms



