version: '3.4'


services:
  server:
    build:
      context: .
      dockerfile: /Service/Dockerfile
    image: recipeapp.service
    container_name: recipeapp.service
    ports:
      - 8081:80

  presentation:
    build:
      context: .
      dockerfile: /Presentation/Dockerfile
    image: recipeapp.presentation
    container_name: recipeapp.presentation
    ports:
      - 8080:80
    depends_on:
      - server

